[package]
name = "unity-rzv-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2      = "0.9"
prost        = "0.12"
anyhow       = "1.0"
memchr       = "2.8.0"
aho-corasick = "1.1.4"
tonic        = "0.11"
tokio        = { version = "1", features = ["full"] }
rusqlite     = { version = "0.31", features = ["bundled"] }
walkdir      = "2"
tokio-stream = "0.1"
tracing                 = "0.1"
tracing-subscriber      = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
tonic-build = "0.11"
